/**
 * Konstanta standar untuk aplikasi hafalan
 * File ini berisi daftar data standar yang digunakan di berbagai bagian aplikasi
 */

// ============================================
// DAFTAR PROVINSI DI INDONESIA (untuk tempat lahir)
// ============================================
export const INDONESIA_PROVINCES = [
  "Aceh",
  "Bali",
  "Bangka Belitung",
  "Banten",
  "Bengkulu",
  "DI Yogyakarta",
  "DKI Jakarta",
  "Gorontalo",
  "Jambi",
  "Jawa Barat",
  "Jawa Tengah",
  "Jawa Timur",
  "Kalimantan Barat",
  "Kalimantan Selatan",
  "Kalimantan Tengah",
  "Kalimantan Timur",
  "Kalimantan Utara",
  "Kepulauan Riau",
  "Lampung",
  "Maluku",
  "Maluku Utara",
  "Nusa Tenggara Barat",
  "Nusa Tenggara Timur",
  "Papua",
  "Papua Barat",
  "Papua Barat Daya",
  "Papua Pegunungan",
  "Papua Selatan",
  "Papua Tengah",
  "Riau",
  "Sulawesi Barat",
  "Sulawesi Selatan",
  "Sulawesi Tengah",
  "Sulawesi Tenggara",
  "Sulawesi Utara",
  "Sumatera Barat",
  "Sumatera Selatan",
  "Sumatera Utara",
];

// ============================================
// DAFTAR KOTA BESAR DI INDONESIA (alternatif untuk tempat lahir)
// ============================================
export const INDONESIA_CITIES = [
  "Ambon",
  "Balikpapan",
  "Banda Aceh",
  "Bandar Lampung",
  "Bandung",
  "Banjarmasin",
  "Batam",
  "Bekasi",
  "Bengkulu",
  "Bogor",
  "Cilegon",
  "Cirebon",
  "Denpasar",
  "Depok",
  "Gorontalo",
  "Jakarta",
  "Jambi",
  "Jayapura",
  "Kediri",
  "Kendari",
  "Kupang",
  "Madiun",
  "Magelang",
  "Makassar",
  "Malang",
  "Manado",
  "Mataram",
  "Medan",
  "Mojokerto",
  "Padang",
  "Palangka Raya",
  "Palembang",
  "Palu",
  "Pangkal Pinang",
  "Pasuruan",
  "Pekalongan",
  "Pekanbaru",
  "Pontianak",
  "Probolinggo",
  "Salatiga",
  "Samarinda",
  "Semarang",
  "Serang",
  "Singkawang",
  "Solo",
  "Sukabumi",
  "Surabaya",
  "Tangerang",
  "Tangerang Selatan",
  "Tanjung Pinang",
  "Tasikmalaya",
  "Tegal",
  "Ternate",
  "Yogyakarta",
];

// ============================================
// DAFTAR PEKERJAAN STANDAR
// ============================================
export const OCCUPATIONS = [
  "Agen Asuransi",
  "Agen Properti",
  "Ahli Gizi",
  "Akuntan",
  "Apoteker",
  "Arsitek",
  "Auditor",
  "Baby Sitter",
  "Banker",
  "Barista",
  "Bidan",
  "Broker",
  "Buruh",
  "Chef/Koki",
  "Cleaning Service",
  "Content Creator",
  "Da'i/Da'iyah",
  "Data Scientist",
  "Desainer Grafis",
  "Direktur",
  "Dokter",
  "Dokter Gigi",
  "Dokter Spesialis",
  "Dosen",
  "Driver Online",
  "Finance",
  "Fotografer",
  "Guru",
  "Honorer",
  "HRD",
  "Ibu Rumah Tangga",
  "Imam Masjid",
  "Insinyur",
  "Investor",
  "Jurnalis",
  "Karyawan Kontrak",
  "Konsultan",
  "Kurir",
  "Lainnya",
  "Mahasiswa",
  "Manajer",
  "Marketing",
  "Montir",
  "Nelayan",
  "Notaris",
  "Pedagang",
  "Pegawai Negeri Sipil (PNS)",
  "Pegawai Swasta",
  "Pembantu Rumah Tangga",
  "Peneliti",
  "Pengacara",
  "Pengusaha",
  "Penjahit",
  "Pensiunan",
  "Penulis",
  "Perawat",
  "Petani",
  "Pilot",
  "Pramugari",
  "Programmer",
  "Psikiater",
  "Psikolog",
  "Sales",
  "Salon/Kapster",
  "Security",
  "Software Engineer",
  "Sopir",
  "Supervisor",
  "Teknisi",
  "Tidak Bekerja",
  "TNI/Polri",
  "Tukang",
  "Ustadz/Ustadzah",
  "Videographer",
  "Wartawan",
  "Wiraswasta",
  "Wirausaha",
  "Youtuber",
];

// ============================================
// DEFAULT PASSWORDS
// ============================================
export const DEFAULT_PASSWORDS = {
  SANTRI: "santri123",
  WALI: "wali123",
  TEACHER: "guru123",
  ADMIN: "admin123",
} as const;

// ============================================
// STATUS HAFALAN
// ============================================
export const HAFALAN_STATUS = {
  PROGRESS: "PROGRESS",
  COMPLETE_WAITING_RECHECK: "COMPLETE_WAITING_RECHECK",
  RECHECK_PASSED: "RECHECK_PASSED",
} as const;

export const HAFALAN_STATUS_LABEL = {
  PROGRESS: "Sedang Hafal",
  COMPLETE_WAITING_RECHECK: "Menunggu Recheck",
  RECHECK_PASSED: "Recheck Selesai",
} as const;
