/**
 * Data Halaman Al-Quran - Bagian 3 (Juz 21-30, Halaman 399-604)
 *
 * Berdasarkan Mushaf Madinah standar (604 halaman)
 */

import { KacaData } from "./quran-pages-1";

// Juz 21: Halaman 402-421 (Al-'Ankabut 46 - Al-Ahzab 30)
export const juz21: KacaData[] = [
  {
    pageNumber: 402,
    surahNumber: 29,
    surahName: "Al-'Ankabut",
    ayatStart: 46,
    ayatEnd: 55,
    juz: 21,
  },
  {
    pageNumber: 403,
    surahNumber: 29,
    surahName: "Al-'Ankabut",
    ayatStart: 56,
    ayatEnd: 64,
    juz: 21,
  },
  {
    pageNumber: 404,
    surahNumber: 29,
    surahName: "Al-'Ankabut",
    ayatStart: 65,
    ayatEnd: 69,
    juz: 21,
  },
  {
    pageNumber: 405,
    surahNumber: 30,
    surahName: "Ar-Rum",
    ayatStart: 1,
    ayatEnd: 10,
    juz: 21,
  },
  {
    pageNumber: 406,
    surahNumber: 30,
    surahName: "Ar-Rum",
    ayatStart: 11,
    ayatEnd: 22,
    juz: 21,
  },
  {
    pageNumber: 407,
    surahNumber: 30,
    surahName: "Ar-Rum",
    ayatStart: 23,
    ayatEnd: 32,
    juz: 21,
  },
  {
    pageNumber: 408,
    surahNumber: 30,
    surahName: "Ar-Rum",
    ayatStart: 33,
    ayatEnd: 42,
    juz: 21,
  },
  {
    pageNumber: 409,
    surahNumber: 30,
    surahName: "Ar-Rum",
    ayatStart: 43,
    ayatEnd: 53,
    juz: 21,
  },
  {
    pageNumber: 410,
    surahNumber: 30,
    surahName: "Ar-Rum",
    ayatStart: 54,
    ayatEnd: 60,
    juz: 21,
  },
  {
    pageNumber: 411,
    surahNumber: 31,
    surahName: "Luqman",
    ayatStart: 1,
    ayatEnd: 11,
    juz: 21,
  },
  {
    pageNumber: 412,
    surahNumber: 31,
    surahName: "Luqman",
    ayatStart: 12,
    ayatEnd: 20,
    juz: 21,
  },
  {
    pageNumber: 413,
    surahNumber: 31,
    surahName: "Luqman",
    ayatStart: 21,
    ayatEnd: 30,
    juz: 21,
  },
  {
    pageNumber: 414,
    surahNumber: 31,
    surahName: "Luqman",
    ayatStart: 31,
    ayatEnd: 34,
    juz: 21,
  },
  {
    pageNumber: 415,
    surahNumber: 32,
    surahName: "As-Sajdah",
    ayatStart: 1,
    ayatEnd: 12,
    juz: 21,
  },
  {
    pageNumber: 416,
    surahNumber: 32,
    surahName: "As-Sajdah",
    ayatStart: 13,
    ayatEnd: 22,
    juz: 21,
  },
  {
    pageNumber: 417,
    surahNumber: 32,
    surahName: "As-Sajdah",
    ayatStart: 23,
    ayatEnd: 30,
    juz: 21,
  },
  {
    pageNumber: 418,
    surahNumber: 33,
    surahName: "Al-Ahzab",
    ayatStart: 1,
    ayatEnd: 7,
    juz: 21,
  },
  {
    pageNumber: 419,
    surahNumber: 33,
    surahName: "Al-Ahzab",
    ayatStart: 8,
    ayatEnd: 17,
    juz: 21,
  },
  {
    pageNumber: 420,
    surahNumber: 33,
    surahName: "Al-Ahzab",
    ayatStart: 18,
    ayatEnd: 25,
    juz: 21,
  },
  {
    pageNumber: 421,
    surahNumber: 33,
    surahName: "Al-Ahzab",
    ayatStart: 26,
    ayatEnd: 30,
    juz: 21,
  },
];

// Juz 22: Halaman 422-441 (Al-Ahzab 31 - Ya-Sin 27)
export const juz22: KacaData[] = [
  {
    pageNumber: 422,
    surahNumber: 33,
    surahName: "Al-Ahzab",
    ayatStart: 31,
    ayatEnd: 37,
    juz: 22,
  },
  {
    pageNumber: 423,
    surahNumber: 33,
    surahName: "Al-Ahzab",
    ayatStart: 38,
    ayatEnd: 44,
    juz: 22,
  },
  {
    pageNumber: 424,
    surahNumber: 33,
    surahName: "Al-Ahzab",
    ayatStart: 45,
    ayatEnd: 52,
    juz: 22,
  },
  {
    pageNumber: 425,
    surahNumber: 33,
    surahName: "Al-Ahzab",
    ayatStart: 53,
    ayatEnd: 57,
    juz: 22,
  },
  {
    pageNumber: 426,
    surahNumber: 33,
    surahName: "Al-Ahzab",
    ayatStart: 58,
    ayatEnd: 66,
    juz: 22,
  },
  {
    pageNumber: 427,
    surahNumber: 33,
    surahName: "Al-Ahzab",
    ayatStart: 67,
    ayatEnd: 73,
    juz: 22,
  },
  {
    pageNumber: 428,
    surahNumber: 34,
    surahName: "Saba'",
    ayatStart: 1,
    ayatEnd: 9,
    juz: 22,
  },
  {
    pageNumber: 429,
    surahNumber: 34,
    surahName: "Saba'",
    ayatStart: 10,
    ayatEnd: 18,
    juz: 22,
  },
  {
    pageNumber: 430,
    surahNumber: 34,
    surahName: "Saba'",
    ayatStart: 19,
    ayatEnd: 26,
    juz: 22,
  },
  {
    pageNumber: 431,
    surahNumber: 34,
    surahName: "Saba'",
    ayatStart: 27,
    ayatEnd: 36,
    juz: 22,
  },
  {
    pageNumber: 432,
    surahNumber: 34,
    surahName: "Saba'",
    ayatStart: 37,
    ayatEnd: 45,
    juz: 22,
  },
  {
    pageNumber: 433,
    surahNumber: 34,
    surahName: "Saba'",
    ayatStart: 46,
    ayatEnd: 54,
    juz: 22,
  },
  {
    pageNumber: 434,
    surahNumber: 35,
    surahName: "Fatir",
    ayatStart: 1,
    ayatEnd: 8,
    juz: 22,
  },
  {
    pageNumber: 435,
    surahNumber: 35,
    surahName: "Fatir",
    ayatStart: 9,
    ayatEnd: 18,
    juz: 22,
  },
  {
    pageNumber: 436,
    surahNumber: 35,
    surahName: "Fatir",
    ayatStart: 19,
    ayatEnd: 30,
    juz: 22,
  },
  {
    pageNumber: 437,
    surahNumber: 35,
    surahName: "Fatir",
    ayatStart: 31,
    ayatEnd: 40,
    juz: 22,
  },
  {
    pageNumber: 438,
    surahNumber: 35,
    surahName: "Fatir",
    ayatStart: 41,
    ayatEnd: 45,
    juz: 22,
  },
  {
    pageNumber: 439,
    surahNumber: 36,
    surahName: "Ya-Sin",
    ayatStart: 1,
    ayatEnd: 12,
    juz: 22,
  },
  {
    pageNumber: 440,
    surahNumber: 36,
    surahName: "Ya-Sin",
    ayatStart: 13,
    ayatEnd: 27,
    juz: 22,
  },
  {
    pageNumber: 441,
    surahNumber: 36,
    surahName: "Ya-Sin",
    ayatStart: 28,
    ayatEnd: 28,
    juz: 22,
  },
];

// Juz 23: Halaman 442-461 (Ya-Sin 28 - Az-Zumar 31)
export const juz23: KacaData[] = [
  {
    pageNumber: 442,
    surahNumber: 36,
    surahName: "Ya-Sin",
    ayatStart: 28,
    ayatEnd: 40,
    juz: 23,
  },
  {
    pageNumber: 443,
    surahNumber: 36,
    surahName: "Ya-Sin",
    ayatStart: 41,
    ayatEnd: 54,
    juz: 23,
  },
  {
    pageNumber: 444,
    surahNumber: 36,
    surahName: "Ya-Sin",
    ayatStart: 55,
    ayatEnd: 70,
    juz: 23,
  },
  {
    pageNumber: 445,
    surahNumber: 36,
    surahName: "Ya-Sin",
    ayatStart: 71,
    ayatEnd: 83,
    juz: 23,
  },
  {
    pageNumber: 446,
    surahNumber: 37,
    surahName: "As-Saffat",
    ayatStart: 1,
    ayatEnd: 24,
    juz: 23,
  },
  {
    pageNumber: 447,
    surahNumber: 37,
    surahName: "As-Saffat",
    ayatStart: 25,
    ayatEnd: 52,
    juz: 23,
  },
  {
    pageNumber: 448,
    surahNumber: 37,
    surahName: "As-Saffat",
    ayatStart: 53,
    ayatEnd: 76,
    juz: 23,
  },
  {
    pageNumber: 449,
    surahNumber: 37,
    surahName: "As-Saffat",
    ayatStart: 77,
    ayatEnd: 102,
    juz: 23,
  },
  {
    pageNumber: 450,
    surahNumber: 37,
    surahName: "As-Saffat",
    ayatStart: 103,
    ayatEnd: 126,
    juz: 23,
  },
  {
    pageNumber: 451,
    surahNumber: 37,
    surahName: "As-Saffat",
    ayatStart: 127,
    ayatEnd: 153,
    juz: 23,
  },
  {
    pageNumber: 452,
    surahNumber: 37,
    surahName: "As-Saffat",
    ayatStart: 154,
    ayatEnd: 182,
    juz: 23,
  },
  {
    pageNumber: 453,
    surahNumber: 38,
    surahName: "Sad",
    ayatStart: 1,
    ayatEnd: 16,
    juz: 23,
  },
  {
    pageNumber: 454,
    surahNumber: 38,
    surahName: "Sad",
    ayatStart: 17,
    ayatEnd: 26,
    juz: 23,
  },
  {
    pageNumber: 455,
    surahNumber: 38,
    surahName: "Sad",
    ayatStart: 27,
    ayatEnd: 42,
    juz: 23,
  },
  {
    pageNumber: 456,
    surahNumber: 38,
    surahName: "Sad",
    ayatStart: 43,
    ayatEnd: 61,
    juz: 23,
  },
  {
    pageNumber: 457,
    surahNumber: 38,
    surahName: "Sad",
    ayatStart: 62,
    ayatEnd: 83,
    juz: 23,
  },
  {
    pageNumber: 458,
    surahNumber: 38,
    surahName: "Sad",
    ayatStart: 84,
    ayatEnd: 88,
    juz: 23,
  },
  {
    pageNumber: 459,
    surahNumber: 39,
    surahName: "Az-Zumar",
    ayatStart: 1,
    ayatEnd: 8,
    juz: 23,
  },
  {
    pageNumber: 460,
    surahNumber: 39,
    surahName: "Az-Zumar",
    ayatStart: 9,
    ayatEnd: 17,
    juz: 23,
  },
  {
    pageNumber: 461,
    surahNumber: 39,
    surahName: "Az-Zumar",
    ayatStart: 18,
    ayatEnd: 31,
    juz: 23,
  },
];

// Juz 24: Halaman 462-481 (Az-Zumar 32 - Fussilat 46)
export const juz24: KacaData[] = [
  {
    pageNumber: 462,
    surahNumber: 39,
    surahName: "Az-Zumar",
    ayatStart: 32,
    ayatEnd: 41,
    juz: 24,
  },
  {
    pageNumber: 463,
    surahNumber: 39,
    surahName: "Az-Zumar",
    ayatStart: 42,
    ayatEnd: 52,
    juz: 24,
  },
  {
    pageNumber: 464,
    surahNumber: 39,
    surahName: "Az-Zumar",
    ayatStart: 53,
    ayatEnd: 63,
    juz: 24,
  },
  {
    pageNumber: 465,
    surahNumber: 39,
    surahName: "Az-Zumar",
    ayatStart: 64,
    ayatEnd: 74,
    juz: 24,
  },
  {
    pageNumber: 466,
    surahNumber: 39,
    surahName: "Az-Zumar",
    ayatStart: 75,
    ayatEnd: 75,
    juz: 24,
  },
  {
    pageNumber: 467,
    surahNumber: 40,
    surahName: "Ghafir",
    ayatStart: 1,
    ayatEnd: 9,
    juz: 24,
  },
  {
    pageNumber: 468,
    surahNumber: 40,
    surahName: "Ghafir",
    ayatStart: 10,
    ayatEnd: 19,
    juz: 24,
  },
  {
    pageNumber: 469,
    surahNumber: 40,
    surahName: "Ghafir",
    ayatStart: 20,
    ayatEnd: 27,
    juz: 24,
  },
  {
    pageNumber: 470,
    surahNumber: 40,
    surahName: "Ghafir",
    ayatStart: 28,
    ayatEnd: 35,
    juz: 24,
  },
  {
    pageNumber: 471,
    surahNumber: 40,
    surahName: "Ghafir",
    ayatStart: 36,
    ayatEnd: 44,
    juz: 24,
  },
  {
    pageNumber: 472,
    surahNumber: 40,
    surahName: "Ghafir",
    ayatStart: 45,
    ayatEnd: 54,
    juz: 24,
  },
  {
    pageNumber: 473,
    surahNumber: 40,
    surahName: "Ghafir",
    ayatStart: 55,
    ayatEnd: 65,
    juz: 24,
  },
  {
    pageNumber: 474,
    surahNumber: 40,
    surahName: "Ghafir",
    ayatStart: 66,
    ayatEnd: 77,
    juz: 24,
  },
  {
    pageNumber: 475,
    surahNumber: 40,
    surahName: "Ghafir",
    ayatStart: 78,
    ayatEnd: 85,
    juz: 24,
  },
  {
    pageNumber: 476,
    surahNumber: 41,
    surahName: "Fussilat",
    ayatStart: 1,
    ayatEnd: 11,
    juz: 24,
  },
  {
    pageNumber: 477,
    surahNumber: 41,
    surahName: "Fussilat",
    ayatStart: 12,
    ayatEnd: 20,
    juz: 24,
  },
  {
    pageNumber: 478,
    surahNumber: 41,
    surahName: "Fussilat",
    ayatStart: 21,
    ayatEnd: 29,
    juz: 24,
  },
  {
    pageNumber: 479,
    surahNumber: 41,
    surahName: "Fussilat",
    ayatStart: 30,
    ayatEnd: 38,
    juz: 24,
  },
  {
    pageNumber: 480,
    surahNumber: 41,
    surahName: "Fussilat",
    ayatStart: 39,
    ayatEnd: 46,
    juz: 24,
  },
  {
    pageNumber: 481,
    surahNumber: 41,
    surahName: "Fussilat",
    ayatStart: 47,
    ayatEnd: 47,
    juz: 24,
  },
];

// Juz 25: Halaman 482-502 (Fussilat 47 - Al-Jatsiyah 37)
export const juz25: KacaData[] = [
  {
    pageNumber: 482,
    surahNumber: 41,
    surahName: "Fussilat",
    ayatStart: 47,
    ayatEnd: 54,
    juz: 25,
  },
  {
    pageNumber: 483,
    surahNumber: 42,
    surahName: "Asy-Syura",
    ayatStart: 1,
    ayatEnd: 10,
    juz: 25,
  },
  {
    pageNumber: 484,
    surahNumber: 42,
    surahName: "Asy-Syura",
    ayatStart: 11,
    ayatEnd: 17,
    juz: 25,
  },
  {
    pageNumber: 485,
    surahNumber: 42,
    surahName: "Asy-Syura",
    ayatStart: 18,
    ayatEnd: 26,
    juz: 25,
  },
  {
    pageNumber: 486,
    surahNumber: 42,
    surahName: "Asy-Syura",
    ayatStart: 27,
    ayatEnd: 35,
    juz: 25,
  },
  {
    pageNumber: 487,
    surahNumber: 42,
    surahName: "Asy-Syura",
    ayatStart: 36,
    ayatEnd: 46,
    juz: 25,
  },
  {
    pageNumber: 488,
    surahNumber: 42,
    surahName: "Asy-Syura",
    ayatStart: 47,
    ayatEnd: 53,
    juz: 25,
  },
  {
    pageNumber: 489,
    surahNumber: 43,
    surahName: "Az-Zukhruf",
    ayatStart: 1,
    ayatEnd: 15,
    juz: 25,
  },
  {
    pageNumber: 490,
    surahNumber: 43,
    surahName: "Az-Zukhruf",
    ayatStart: 16,
    ayatEnd: 29,
    juz: 25,
  },
  {
    pageNumber: 491,
    surahNumber: 43,
    surahName: "Az-Zukhruf",
    ayatStart: 30,
    ayatEnd: 43,
    juz: 25,
  },
  {
    pageNumber: 492,
    surahNumber: 43,
    surahName: "Az-Zukhruf",
    ayatStart: 44,
    ayatEnd: 56,
    juz: 25,
  },
  {
    pageNumber: 493,
    surahNumber: 43,
    surahName: "Az-Zukhruf",
    ayatStart: 57,
    ayatEnd: 73,
    juz: 25,
  },
  {
    pageNumber: 494,
    surahNumber: 43,
    surahName: "Az-Zukhruf",
    ayatStart: 74,
    ayatEnd: 89,
    juz: 25,
  },
  {
    pageNumber: 495,
    surahNumber: 44,
    surahName: "Ad-Dukhan",
    ayatStart: 1,
    ayatEnd: 19,
    juz: 25,
  },
  {
    pageNumber: 496,
    surahNumber: 44,
    surahName: "Ad-Dukhan",
    ayatStart: 20,
    ayatEnd: 44,
    juz: 25,
  },
  {
    pageNumber: 497,
    surahNumber: 44,
    surahName: "Ad-Dukhan",
    ayatStart: 45,
    ayatEnd: 59,
    juz: 25,
  },
  {
    pageNumber: 498,
    surahNumber: 45,
    surahName: "Al-Jatsiyah",
    ayatStart: 1,
    ayatEnd: 14,
    juz: 25,
  },
  {
    pageNumber: 499,
    surahNumber: 45,
    surahName: "Al-Jatsiyah",
    ayatStart: 15,
    ayatEnd: 26,
    juz: 25,
  },
  {
    pageNumber: 500,
    surahNumber: 45,
    surahName: "Al-Jatsiyah",
    ayatStart: 27,
    ayatEnd: 37,
    juz: 25,
  },
  {
    pageNumber: 501,
    surahNumber: 46,
    surahName: "Al-Ahqaf",
    ayatStart: 1,
    ayatEnd: 5,
    juz: 25,
  },
  {
    pageNumber: 502,
    surahNumber: 46,
    surahName: "Al-Ahqaf",
    ayatStart: 6,
    ayatEnd: 6,
    juz: 25,
  },
];

// Juz 26: Halaman 502-521 (Al-Ahqaf 1 - Adz-Dzariyat 30)
export const juz26: KacaData[] = [
  {
    pageNumber: 502,
    surahNumber: 46,
    surahName: "Al-Ahqaf",
    ayatStart: 1,
    ayatEnd: 10,
    juz: 26,
  },
  {
    pageNumber: 503,
    surahNumber: 46,
    surahName: "Al-Ahqaf",
    ayatStart: 11,
    ayatEnd: 20,
    juz: 26,
  },
  {
    pageNumber: 504,
    surahNumber: 46,
    surahName: "Al-Ahqaf",
    ayatStart: 21,
    ayatEnd: 28,
    juz: 26,
  },
  {
    pageNumber: 505,
    surahNumber: 46,
    surahName: "Al-Ahqaf",
    ayatStart: 29,
    ayatEnd: 35,
    juz: 26,
  },
  {
    pageNumber: 506,
    surahNumber: 47,
    surahName: "Muhammad",
    ayatStart: 1,
    ayatEnd: 11,
    juz: 26,
  },
  {
    pageNumber: 507,
    surahNumber: 47,
    surahName: "Muhammad",
    ayatStart: 12,
    ayatEnd: 20,
    juz: 26,
  },
  {
    pageNumber: 508,
    surahNumber: 47,
    surahName: "Muhammad",
    ayatStart: 21,
    ayatEnd: 30,
    juz: 26,
  },
  {
    pageNumber: 509,
    surahNumber: 47,
    surahName: "Muhammad",
    ayatStart: 31,
    ayatEnd: 38,
    juz: 26,
  },
  {
    pageNumber: 510,
    surahNumber: 48,
    surahName: "Al-Fath",
    ayatStart: 1,
    ayatEnd: 9,
    juz: 26,
  },
  {
    pageNumber: 511,
    surahNumber: 48,
    surahName: "Al-Fath",
    ayatStart: 10,
    ayatEnd: 17,
    juz: 26,
  },
  {
    pageNumber: 512,
    surahNumber: 48,
    surahName: "Al-Fath",
    ayatStart: 18,
    ayatEnd: 25,
    juz: 26,
  },
  {
    pageNumber: 513,
    surahNumber: 48,
    surahName: "Al-Fath",
    ayatStart: 26,
    ayatEnd: 29,
    juz: 26,
  },
  {
    pageNumber: 514,
    surahNumber: 49,
    surahName: "Al-Hujurat",
    ayatStart: 1,
    ayatEnd: 9,
    juz: 26,
  },
  {
    pageNumber: 515,
    surahNumber: 49,
    surahName: "Al-Hujurat",
    ayatStart: 10,
    ayatEnd: 18,
    juz: 26,
  },
  {
    pageNumber: 516,
    surahNumber: 50,
    surahName: "Qaf",
    ayatStart: 1,
    ayatEnd: 15,
    juz: 26,
  },
  {
    pageNumber: 517,
    surahNumber: 50,
    surahName: "Qaf",
    ayatStart: 16,
    ayatEnd: 35,
    juz: 26,
  },
  {
    pageNumber: 518,
    surahNumber: 50,
    surahName: "Qaf",
    ayatStart: 36,
    ayatEnd: 45,
    juz: 26,
  },
  {
    pageNumber: 519,
    surahNumber: 51,
    surahName: "Adz-Dzariyat",
    ayatStart: 1,
    ayatEnd: 23,
    juz: 26,
  },
  {
    pageNumber: 520,
    surahNumber: 51,
    surahName: "Adz-Dzariyat",
    ayatStart: 24,
    ayatEnd: 46,
    juz: 26,
  },
  {
    pageNumber: 521,
    surahNumber: 51,
    surahName: "Adz-Dzariyat",
    ayatStart: 47,
    ayatEnd: 60,
    juz: 26,
  },
];

// Juz 27: Halaman 522-541 (Adz-Dzariyat 31 - Al-Hadid 29)
export const juz27: KacaData[] = [
  {
    pageNumber: 522,
    surahNumber: 51,
    surahName: "Adz-Dzariyat",
    ayatStart: 31,
    ayatEnd: 60,
    juz: 27,
  },
  {
    pageNumber: 523,
    surahNumber: 52,
    surahName: "At-Tur",
    ayatStart: 1,
    ayatEnd: 23,
    juz: 27,
  },
  {
    pageNumber: 524,
    surahNumber: 52,
    surahName: "At-Tur",
    ayatStart: 24,
    ayatEnd: 49,
    juz: 27,
  },
  {
    pageNumber: 525,
    surahNumber: 53,
    surahName: "An-Najm",
    ayatStart: 1,
    ayatEnd: 25,
    juz: 27,
  },
  {
    pageNumber: 526,
    surahNumber: 53,
    surahName: "An-Najm",
    ayatStart: 26,
    ayatEnd: 62,
    juz: 27,
  },
  {
    pageNumber: 527,
    surahNumber: 54,
    surahName: "Al-Qamar",
    ayatStart: 1,
    ayatEnd: 22,
    juz: 27,
  },
  {
    pageNumber: 528,
    surahNumber: 54,
    surahName: "Al-Qamar",
    ayatStart: 23,
    ayatEnd: 55,
    juz: 27,
  },
  {
    pageNumber: 529,
    surahNumber: 55,
    surahName: "Ar-Rahman",
    ayatStart: 1,
    ayatEnd: 25,
    juz: 27,
  },
  {
    pageNumber: 530,
    surahNumber: 55,
    surahName: "Ar-Rahman",
    ayatStart: 26,
    ayatEnd: 55,
    juz: 27,
  },
  {
    pageNumber: 531,
    surahNumber: 55,
    surahName: "Ar-Rahman",
    ayatStart: 56,
    ayatEnd: 78,
    juz: 27,
  },
  {
    pageNumber: 532,
    surahNumber: 56,
    surahName: "Al-Waqi'ah",
    ayatStart: 1,
    ayatEnd: 26,
    juz: 27,
  },
  {
    pageNumber: 533,
    surahNumber: 56,
    surahName: "Al-Waqi'ah",
    ayatStart: 27,
    ayatEnd: 54,
    juz: 27,
  },
  {
    pageNumber: 534,
    surahNumber: 56,
    surahName: "Al-Waqi'ah",
    ayatStart: 55,
    ayatEnd: 82,
    juz: 27,
  },
  {
    pageNumber: 535,
    surahNumber: 56,
    surahName: "Al-Waqi'ah",
    ayatStart: 83,
    ayatEnd: 96,
    juz: 27,
  },
  {
    pageNumber: 536,
    surahNumber: 57,
    surahName: "Al-Hadid",
    ayatStart: 1,
    ayatEnd: 10,
    juz: 27,
  },
  {
    pageNumber: 537,
    surahNumber: 57,
    surahName: "Al-Hadid",
    ayatStart: 11,
    ayatEnd: 18,
    juz: 27,
  },
  {
    pageNumber: 538,
    surahNumber: 57,
    surahName: "Al-Hadid",
    ayatStart: 19,
    ayatEnd: 25,
    juz: 27,
  },
  {
    pageNumber: 539,
    surahNumber: 57,
    surahName: "Al-Hadid",
    ayatStart: 26,
    ayatEnd: 29,
    juz: 27,
  },
  {
    pageNumber: 540,
    surahNumber: 58,
    surahName: "Al-Mujadilah",
    ayatStart: 1,
    ayatEnd: 6,
    juz: 27,
  },
  {
    pageNumber: 541,
    surahNumber: 58,
    surahName: "Al-Mujadilah",
    ayatStart: 7,
    ayatEnd: 7,
    juz: 27,
  },
];

// Juz 28: Halaman 542-561 (Al-Mujadilah 1 - At-Tahrim 12)
export const juz28: KacaData[] = [
  {
    pageNumber: 542,
    surahNumber: 58,
    surahName: "Al-Mujadilah",
    ayatStart: 1,
    ayatEnd: 8,
    juz: 28,
  },
  {
    pageNumber: 543,
    surahNumber: 58,
    surahName: "Al-Mujadilah",
    ayatStart: 9,
    ayatEnd: 17,
    juz: 28,
  },
  {
    pageNumber: 544,
    surahNumber: 58,
    surahName: "Al-Mujadilah",
    ayatStart: 18,
    ayatEnd: 22,
    juz: 28,
  },
  {
    pageNumber: 545,
    surahNumber: 59,
    surahName: "Al-Hasyr",
    ayatStart: 1,
    ayatEnd: 7,
    juz: 28,
  },
  {
    pageNumber: 546,
    surahNumber: 59,
    surahName: "Al-Hasyr",
    ayatStart: 8,
    ayatEnd: 14,
    juz: 28,
  },
  {
    pageNumber: 547,
    surahNumber: 59,
    surahName: "Al-Hasyr",
    ayatStart: 15,
    ayatEnd: 21,
    juz: 28,
  },
  {
    pageNumber: 548,
    surahNumber: 59,
    surahName: "Al-Hasyr",
    ayatStart: 22,
    ayatEnd: 24,
    juz: 28,
  },
  {
    pageNumber: 549,
    surahNumber: 60,
    surahName: "Al-Mumtahanah",
    ayatStart: 1,
    ayatEnd: 6,
    juz: 28,
  },
  {
    pageNumber: 550,
    surahNumber: 60,
    surahName: "Al-Mumtahanah",
    ayatStart: 7,
    ayatEnd: 13,
    juz: 28,
  },
  {
    pageNumber: 551,
    surahNumber: 61,
    surahName: "As-Saff",
    ayatStart: 1,
    ayatEnd: 14,
    juz: 28,
  },
  {
    pageNumber: 552,
    surahNumber: 62,
    surahName: "Al-Jumu'ah",
    ayatStart: 1,
    ayatEnd: 11,
    juz: 28,
  },
  {
    pageNumber: 553,
    surahNumber: 63,
    surahName: "Al-Munafiqun",
    ayatStart: 1,
    ayatEnd: 11,
    juz: 28,
  },
  {
    pageNumber: 554,
    surahNumber: 64,
    surahName: "At-Taghabun",
    ayatStart: 1,
    ayatEnd: 10,
    juz: 28,
  },
  {
    pageNumber: 555,
    surahNumber: 64,
    surahName: "At-Taghabun",
    ayatStart: 11,
    ayatEnd: 18,
    juz: 28,
  },
  {
    pageNumber: 556,
    surahNumber: 65,
    surahName: "At-Talaq",
    ayatStart: 1,
    ayatEnd: 6,
    juz: 28,
  },
  {
    pageNumber: 557,
    surahNumber: 65,
    surahName: "At-Talaq",
    ayatStart: 7,
    ayatEnd: 12,
    juz: 28,
  },
  {
    pageNumber: 558,
    surahNumber: 66,
    surahName: "At-Tahrim",
    ayatStart: 1,
    ayatEnd: 7,
    juz: 28,
  },
  {
    pageNumber: 559,
    surahNumber: 66,
    surahName: "At-Tahrim",
    ayatStart: 8,
    ayatEnd: 12,
    juz: 28,
  },
  {
    pageNumber: 560,
    surahNumber: 67,
    surahName: "Al-Mulk",
    ayatStart: 1,
    ayatEnd: 13,
    juz: 28,
  },
  {
    pageNumber: 561,
    surahNumber: 67,
    surahName: "Al-Mulk",
    ayatStart: 14,
    ayatEnd: 14,
    juz: 28,
  },
];

// Juz 29: Halaman 562-581 (Al-Mulk 1 - Al-Mursalat 50)
export const juz29: KacaData[] = [
  {
    pageNumber: 562,
    surahNumber: 67,
    surahName: "Al-Mulk",
    ayatStart: 1,
    ayatEnd: 14,
    juz: 29,
  },
  {
    pageNumber: 563,
    surahNumber: 67,
    surahName: "Al-Mulk",
    ayatStart: 15,
    ayatEnd: 30,
    juz: 29,
  },
  {
    pageNumber: 564,
    surahNumber: 68,
    surahName: "Al-Qalam",
    ayatStart: 1,
    ayatEnd: 18,
    juz: 29,
  },
  {
    pageNumber: 565,
    surahNumber: 68,
    surahName: "Al-Qalam",
    ayatStart: 19,
    ayatEnd: 43,
    juz: 29,
  },
  {
    pageNumber: 566,
    surahNumber: 68,
    surahName: "Al-Qalam",
    ayatStart: 44,
    ayatEnd: 52,
    juz: 29,
  },
  {
    pageNumber: 567,
    surahNumber: 69,
    surahName: "Al-Haqqah",
    ayatStart: 1,
    ayatEnd: 24,
    juz: 29,
  },
  {
    pageNumber: 568,
    surahNumber: 69,
    surahName: "Al-Haqqah",
    ayatStart: 25,
    ayatEnd: 52,
    juz: 29,
  },
  {
    pageNumber: 569,
    surahNumber: 70,
    surahName: "Al-Ma'arij",
    ayatStart: 1,
    ayatEnd: 26,
    juz: 29,
  },
  {
    pageNumber: 570,
    surahNumber: 70,
    surahName: "Al-Ma'arij",
    ayatStart: 27,
    ayatEnd: 44,
    juz: 29,
  },
  {
    pageNumber: 571,
    surahNumber: 71,
    surahName: "Nuh",
    ayatStart: 1,
    ayatEnd: 28,
    juz: 29,
  },
  {
    pageNumber: 572,
    surahNumber: 72,
    surahName: "Al-Jinn",
    ayatStart: 1,
    ayatEnd: 14,
    juz: 29,
  },
  {
    pageNumber: 573,
    surahNumber: 72,
    surahName: "Al-Jinn",
    ayatStart: 15,
    ayatEnd: 28,
    juz: 29,
  },
  {
    pageNumber: 574,
    surahNumber: 73,
    surahName: "Al-Muzzammil",
    ayatStart: 1,
    ayatEnd: 19,
    juz: 29,
  },
  {
    pageNumber: 575,
    surahNumber: 73,
    surahName: "Al-Muzzammil",
    ayatStart: 20,
    ayatEnd: 20,
    juz: 29,
  },
  {
    pageNumber: 576,
    surahNumber: 74,
    surahName: "Al-Muddatstsir",
    ayatStart: 1,
    ayatEnd: 31,
    juz: 29,
  },
  {
    pageNumber: 577,
    surahNumber: 74,
    surahName: "Al-Muddatstsir",
    ayatStart: 32,
    ayatEnd: 56,
    juz: 29,
  },
  {
    pageNumber: 578,
    surahNumber: 75,
    surahName: "Al-Qiyamah",
    ayatStart: 1,
    ayatEnd: 30,
    juz: 29,
  },
  {
    pageNumber: 579,
    surahNumber: 75,
    surahName: "Al-Qiyamah",
    ayatStart: 31,
    ayatEnd: 40,
    juz: 29,
  },
  {
    pageNumber: 580,
    surahNumber: 76,
    surahName: "Al-Insan",
    ayatStart: 1,
    ayatEnd: 18,
    juz: 29,
  },
  {
    pageNumber: 581,
    surahNumber: 76,
    surahName: "Al-Insan",
    ayatStart: 19,
    ayatEnd: 31,
    juz: 29,
  },
];

// Juz 30: Halaman 582-604 (An-Naba' 1 - An-Nas 6) - Juz Amma
export const juz30: KacaData[] = [
  {
    pageNumber: 582,
    surahNumber: 77,
    surahName: "Al-Mursalat",
    ayatStart: 1,
    ayatEnd: 32,
    juz: 30,
  },
  {
    pageNumber: 583,
    surahNumber: 77,
    surahName: "Al-Mursalat",
    ayatStart: 33,
    ayatEnd: 50,
    juz: 30,
  },
  {
    pageNumber: 584,
    surahNumber: 78,
    surahName: "An-Naba'",
    ayatStart: 1,
    ayatEnd: 30,
    juz: 30,
  },
  {
    pageNumber: 585,
    surahNumber: 78,
    surahName: "An-Naba'",
    ayatStart: 31,
    ayatEnd: 40,
    juz: 30,
  },
  {
    pageNumber: 586,
    surahNumber: 79,
    surahName: "An-Nazi'at",
    ayatStart: 1,
    ayatEnd: 26,
    juz: 30,
  },
  {
    pageNumber: 587,
    surahNumber: 79,
    surahName: "An-Nazi'at",
    ayatStart: 27,
    ayatEnd: 46,
    juz: 30,
  },
  {
    pageNumber: 588,
    surahNumber: 80,
    surahName: "'Abasa",
    ayatStart: 1,
    ayatEnd: 23,
    juz: 30,
  },
  {
    pageNumber: 589,
    surahNumber: 80,
    surahName: "'Abasa",
    ayatStart: 24,
    ayatEnd: 42,
    juz: 30,
  },
  {
    pageNumber: 590,
    surahNumber: 81,
    surahName: "At-Takwir",
    ayatStart: 1,
    ayatEnd: 29,
    juz: 30,
  },
  {
    pageNumber: 591,
    surahNumber: 82,
    surahName: "Al-Infitar",
    ayatStart: 1,
    ayatEnd: 19,
    juz: 30,
  },
  {
    pageNumber: 592,
    surahNumber: 83,
    surahName: "Al-Mutaffifin",
    ayatStart: 1,
    ayatEnd: 18,
    juz: 30,
  },
  {
    pageNumber: 593,
    surahNumber: 83,
    surahName: "Al-Mutaffifin",
    ayatStart: 19,
    ayatEnd: 36,
    juz: 30,
  },
  {
    pageNumber: 594,
    surahNumber: 84,
    surahName: "Al-Insyiqaq",
    ayatStart: 1,
    ayatEnd: 15,
    juz: 30,
  },
  {
    pageNumber: 595,
    surahNumber: 84,
    surahName: "Al-Insyiqaq",
    ayatStart: 16,
    ayatEnd: 25,
    juz: 30,
  },
  {
    pageNumber: 596,
    surahNumber: 85,
    surahName: "Al-Buruj",
    ayatStart: 1,
    ayatEnd: 22,
    juz: 30,
  },
  {
    pageNumber: 597,
    surahNumber: 86,
    surahName: "At-Tariq",
    ayatStart: 1,
    ayatEnd: 17,
    juz: 30,
  },
  {
    pageNumber: 598,
    surahNumber: 87,
    surahName: "Al-A'la",
    ayatStart: 1,
    ayatEnd: 19,
    juz: 30,
  },
  {
    pageNumber: 599,
    surahNumber: 88,
    surahName: "Al-Ghasyiyah",
    ayatStart: 1,
    ayatEnd: 26,
    juz: 30,
  },
  {
    pageNumber: 600,
    surahNumber: 89,
    surahName: "Al-Fajr",
    ayatStart: 1,
    ayatEnd: 23,
    juz: 30,
  },
  {
    pageNumber: 601,
    surahNumber: 89,
    surahName: "Al-Fajr",
    ayatStart: 24,
    ayatEnd: 30,
    juz: 30,
  },
  {
    pageNumber: 602,
    surahNumber: 90,
    surahName: "Al-Balad",
    ayatStart: 1,
    ayatEnd: 20,
    juz: 30,
  },
  {
    pageNumber: 603,
    surahNumber: 91,
    surahName: "Asy-Syams",
    ayatStart: 1,
    ayatEnd: 15,
    juz: 30,
  },
  {
    pageNumber: 604,
    surahNumber: 92,
    surahName: "Al-Lail",
    ayatStart: 1,
    ayatEnd: 21,
    juz: 30,
  },
];

// Surah-surah pendek di halaman 604 (biasanya digabung)
export const juz30Extra: KacaData[] = [
  {
    pageNumber: 604,
    surahNumber: 93,
    surahName: "Ad-Duha",
    ayatStart: 1,
    ayatEnd: 11,
    juz: 30,
  },
  {
    pageNumber: 604,
    surahNumber: 94,
    surahName: "Asy-Syarh",
    ayatStart: 1,
    ayatEnd: 8,
    juz: 30,
  },
  {
    pageNumber: 604,
    surahNumber: 95,
    surahName: "At-Tin",
    ayatStart: 1,
    ayatEnd: 8,
    juz: 30,
  },
  {
    pageNumber: 604,
    surahNumber: 96,
    surahName: "Al-'Alaq",
    ayatStart: 1,
    ayatEnd: 19,
    juz: 30,
  },
  {
    pageNumber: 604,
    surahNumber: 97,
    surahName: "Al-Qadr",
    ayatStart: 1,
    ayatEnd: 5,
    juz: 30,
  },
  {
    pageNumber: 604,
    surahNumber: 98,
    surahName: "Al-Bayyinah",
    ayatStart: 1,
    ayatEnd: 8,
    juz: 30,
  },
  {
    pageNumber: 604,
    surahNumber: 99,
    surahName: "Az-Zalzalah",
    ayatStart: 1,
    ayatEnd: 8,
    juz: 30,
  },
  {
    pageNumber: 604,
    surahNumber: 100,
    surahName: "Al-'Adiyat",
    ayatStart: 1,
    ayatEnd: 11,
    juz: 30,
  },
  {
    pageNumber: 604,
    surahNumber: 101,
    surahName: "Al-Qari'ah",
    ayatStart: 1,
    ayatEnd: 11,
    juz: 30,
  },
  {
    pageNumber: 604,
    surahNumber: 102,
    surahName: "At-Takatsur",
    ayatStart: 1,
    ayatEnd: 8,
    juz: 30,
  },
  {
    pageNumber: 604,
    surahNumber: 103,
    surahName: "Al-'Asr",
    ayatStart: 1,
    ayatEnd: 3,
    juz: 30,
  },
  {
    pageNumber: 604,
    surahNumber: 104,
    surahName: "Al-Humazah",
    ayatStart: 1,
    ayatEnd: 9,
    juz: 30,
  },
  {
    pageNumber: 604,
    surahNumber: 105,
    surahName: "Al-Fil",
    ayatStart: 1,
    ayatEnd: 5,
    juz: 30,
  },
  {
    pageNumber: 604,
    surahNumber: 106,
    surahName: "Quraisy",
    ayatStart: 1,
    ayatEnd: 4,
    juz: 30,
  },
  {
    pageNumber: 604,
    surahNumber: 107,
    surahName: "Al-Ma'un",
    ayatStart: 1,
    ayatEnd: 7,
    juz: 30,
  },
  {
    pageNumber: 604,
    surahNumber: 108,
    surahName: "Al-Kautsar",
    ayatStart: 1,
    ayatEnd: 3,
    juz: 30,
  },
  {
    pageNumber: 604,
    surahNumber: 109,
    surahName: "Al-Kafirun",
    ayatStart: 1,
    ayatEnd: 6,
    juz: 30,
  },
  {
    pageNumber: 604,
    surahNumber: 110,
    surahName: "An-Nasr",
    ayatStart: 1,
    ayatEnd: 3,
    juz: 30,
  },
  {
    pageNumber: 604,
    surahNumber: 111,
    surahName: "Al-Lahab",
    ayatStart: 1,
    ayatEnd: 5,
    juz: 30,
  },
  {
    pageNumber: 604,
    surahNumber: 112,
    surahName: "Al-Ikhlas",
    ayatStart: 1,
    ayatEnd: 4,
    juz: 30,
  },
  {
    pageNumber: 604,
    surahNumber: 113,
    surahName: "Al-Falaq",
    ayatStart: 1,
    ayatEnd: 5,
    juz: 30,
  },
  {
    pageNumber: 604,
    surahNumber: 114,
    surahName: "An-Nas",
    ayatStart: 1,
    ayatEnd: 6,
    juz: 30,
  },
];

// Export semua juz 21-30
export const quranPagesJuz21to30: KacaData[] = [
  ...juz21,
  ...juz22,
  ...juz23,
  ...juz24,
  ...juz25,
  ...juz26,
  ...juz27,
  ...juz28,
  ...juz29,
  ...juz30,
  ...juz30Extra,
];
